language: node_js
node_js:
- 8
before_install:
- openssl aes-256-cbc -K $encrypted_f7bd7c62657c_key -iv $encrypted_f7bd7c62657c_iv
  -in settings-staging-baserates.json.enc -out settings-staging-baserates.secret
  -d
- openssl aes-256-cbc -K $encrypted_f7bd7c62657c_key -iv $encrypted_f7bd7c62657c_iv
  -in settings-staging-lessestwrong.json.enc -out settings-staging-lessestwrong.json
  -d
- openssl aes-256-cbc -K $encrypted_f7bd7c62657c_key -iv $encrypted_f7bd7c62657c_iv
  -in mup-baserates.js.enc -out mup-baserates.secret 
  -d
- curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/dca8e51fafd60d9e5a8285b07ca34a63f22a5ed4/configure.sh
  | /bin/sh
before_script:
- export PATH=$HOME/.meteor:$PATH
- yarn add -g mup https://github.com/jimrandomh/mup-aws-beanstalk
- yarn add -g json
- yarn add -g @sentry/cli
env:
  global:
    secure: KH6jJVUc12ocK5FyWmDMWeBQZKpEXmpmAyLHnMW4SVxeMCsUCnbKf3sC79ChwTPPEyBWZ4b3Y+lAdNDMhvk3U58QmyjYdPbbEyKK384uvrRrJ//fcg+kQcymEi56V1sZ7qq25G0YZUQOPsv/PnE17AW2fDKrD/50vcCU/zn3hjrilVr4Qwb8act0jCJXZo0TXN5P3qwrsAD7g9cENpIRK3VOldmZALeps1VmXnXbG8zcwAJ8AHSh64WfkXdDLXAkQdnYybyVXUFR9k3gicouy3Mf6rR/N+0gGDItifaWneqCYAXPVg7r6lt9fuHGwbTAUyoV1/zPDfN/7CRGQd0LDHG9f0tThFo/ijJtdQTJeohchuB5XwSABr7rKdfvXtuAz/RJ7Hy9BZZBs8e6/RkA6QLj3VEFejAM+ncP+J/aNwAKJyvAFaKTGUZJKrXkQQ1Y5APEQ1S2SPwRTHUxIgoEMl0yflyJ7nrJpcfTDPtxWFG2tONnMn2J70KBo8yQmHpGyd1hPnLZUvdNdHJsYkuXnYQ13vtOT6sZt6fS4kaJRX4Uxf5u3Flq6KhN3BYty2T9ECc6hTyTdnKHmI/3FGsPEfHi/WWO8B/ylukT4y4h6vyvP+GBPeUNXFbRLmnk8dOrU3DqNd1Ta/PZwopLInbtxvyKKWiH7vJB/nad5Al0iO4=
jobs:
  include:
  - stage: test
    script: yarn run test
  - stage: deploy baserates
    script: mup deploy --config mup.secret --settings settings-staging-baserates.secret
