language: node_js
node_js:
  - "0.10"
before_install:
  - curl https://install.meteor.com | /bin/sh

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - JASMINE_BROWSER=Firefox meteor --test