language: node_js
cache: false
python: 3.7
node_js:
- 14
before_install:
- yarn install
env:
  global:
  - secure: KH6jJVUc12ocK5FyWmDMWeBQZKpEXmpmAyLHnMW4SVxeMCsUCnbKf3sC79ChwTPPEyBWZ4b3Y+lAdNDMhvk3U58QmyjYdPbbEyKK384uvrRrJ//fcg+kQcymEi56V1sZ7qq25G0YZUQOPsv/PnE17AW2fDKrD/50vcCU/zn3hjrilVr4Qwb8act0jCJXZo0TXN5P3qwrsAD7g9cENpIRK3VOldmZALeps1VmXnXbG8zcwAJ8AHSh64WfkXdDLXAkQdnYybyVXUFR9k3gicouy3Mf6rR/N+0gGDItifaWneqCYAXPVg7r6lt9fuHGwbTAUyoV1/zPDfN/7CRGQd0LDHG9f0tThFo/ijJtdQTJeohchuB5XwSABr7rKdfvXtuAz/RJ7Hy9BZZBs8e6/RkA6QLj3VEFejAM+ncP+J/aNwAKJyvAFaKTGUZJKrXkQQ1Y5APEQ1S2SPwRTHUxIgoEMl0yflyJ7nrJpcfTDPtxWFG2tONnMn2J70KBo8yQmHpGyd1hPnLZUvdNdHJsYkuXnYQ13vtOT6sZt6fS4kaJRX4Uxf5u3Flq6KhN3BYty2T9ECc6hTyTdnKHmI/3FGsPEfHi/WWO8B/ylukT4y4h6vyvP+GBPeUNXFbRLmnk8dOrU3DqNd1Ta/PZwopLInbtxvyKKWiH7vJB/nad5Al0iO4=
  - secure: rXw5vCn+dOVJvMAdnvW0j+t1hSY1I5pvk7vyXgLy4b1XKX/dJ8AJCOfeKGTcIlpKPYj4CipQn1g2yqVznBRhRNylt4rdCRSCIgZE0zUXSw9nDJ4OTz9mGW0gSEvHvCntlCcnG3UR8sO4WBJxysycpC37x8XyoGeRj5yEhahNqkh1U5R7ZVDlJKfo+el+FbFe2poOgffCrBahAYEMy5vtTVmnb+vwAejq2/1nS20EwxieVP3maroMalWkQKLkku9s10SpgQvK9FmCr02FWew7NnouzSROZr+t3mL0xv9CHN/6/83tSd+lDJFfRitHTImcQfIbvKoNpnPVqRuLemB7Jo6BWU/NlKcR0/s0Ef1ewT3ONrSrk41/8pRB0Vm24gc1EAL0Uzi9vl4PDQsEf4vxEt5AAdL2aJemVSRWORs5Wvm1qdB6hgYTzedZV/+pXFQrot8Fw1SzlHhb3ASm8/qTJIHNPCXUDHQgbNN1MconZoTDDjeythe2GyfnfCLMq0aMDGp1nes4CA/8miLkubm5iD9VgXiWAVPXxxWifwx59uph12OooFMWpNQHH7MoztflAsMTQ/bbHRVibp0J5FlGYxncOjCNJwgtShpEA2mICGB2IG75cu4asmDprABK7MP+qEe01hpL2dzGuxBY8/ckIwcbsEOQItPiRMmr7KXXz8c=
  - SENTRY_ORG=lesswrong
  - secure: EpMeTiZqRWHXtH8/QTGMsVWcwhIS45zC9p3xMqO5DqZhv0jL4w3A1YzT50+AqKa8ane/ufNnm4Q/vctOngyObM8Sv0OlbHgzrtYROygyZnoGhfC4bZweuvtqX+c0NPYhyxlwZp6NxL2BQx41I0VaZemuvsiOnBXaZ5koO3kZFa2OiQmfHLCzLddOessBLxQvyrIqIw1imZNRLrJ+Pas/1LvFZa7e7zBoBwbimWJRuOJCILe7uwMTHFJqfOeK9uSVfg2lihAqMk3UE3lJR07LyyMFBpDNrrra1OjFKwvFuI2mfQE+s2NdgVFYoBpV3U1phRJ/79FD65mRIPabCZW8QP4VImdb/5GxojPMcY2ebTBrGX0FlDzbNhb+PZgovFiddMmNAOF7qrVzkaTl3OVBjv9B0loJ0nsVRCbg6E5AX47mIy3Ei8hqnVr35pmYkwaA4u+Gpry3RulJmdL5ddNT+vSv0gXuU2FVS6qdSMAyXGgH8mXdAF+ygpqw5bSBI+NDJ0JztA0RfSldI2cUl+62mkHpjvbBxc869mEZsf8oxqq1ONqoq1A8plefyhKMZS+9pYfbX4TCAQk4/xKJEHUuj9sZGqHeSF46zInRuQK/rKq+/iA7I/iUXK3G+UcFCr6nCb9X9GRQpsNL0s/BMUv/354ydChnnbk5LUoA2BtTZxw=
jobs:
  include:
  - stage: everything
    name: "Tests"
    script: yarn run test
  - script: skip
    name: "Deploy LessestWrong"
    if: branch = devel AND type != pull_request
    deploy: &lessestwrong
      provider: script
      script: bash ./deploy.sh ./LessWrong-Credentials/settings-staging-lessestwrong.json ./LessWrong-Credentials/mup-lessestwrong.secret
      on:
        branch: devel
  - script: skip
    name: "Deploy Baserates"
    if: branch = devel AND type != pull_request
    deploy: &baserates
      provider: script
      script: 
        bash ./deploy.sh ./LessWrong-Credentials/settings-staging-baserates.json ./LessWrong-Credentials/mup-baserates.secret
      on:
        branch: devel
  - script: skip
    name: "Deploy LessWrong"
    if: branch = master AND type != pull_request
    deploy: &lesswrong
      provider: script
      script: 
        bash ./deploy.sh ./LessWrong-Credentials/settings-production-lesswrong.json ./LessWrong-Credentials/mup-production.secret
      on:
        branch: master
  - script: skip
    name: "Deploy AIAF"
    if: branch = master AND type != pull_request
    deploy: &AIAF
      provider: script
      script: 
        bash ./deploy.sh ./LessWrong-Credentials/settings-production-alignmentforum.json ./LessWrong-Credentials/mup-af.secret
      on:
        branch: master
