language: node_js
cache: false
python: 3.7
node_js:
- 8
before_install:
- openssl aes-256-cbc -K $encrypted_f7bd7c62657c_key -iv $encrypted_f7bd7c62657c_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- yarn install
- command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com | /bin/sh
before_script:
- tar xvf credentials.tar.gz --strip-components=1 
- export PATH=$HOME/.meteor:$PATH
- yarn global add mup https://github.com/jimrandomh/mup-aws-beanstalk
- yarn global add json
- yarn global add @sentry/cli
env:
  global:
    secure: KH6jJVUc12ocK5FyWmDMWeBQZKpEXmpmAyLHnMW4SVxeMCsUCnbKf3sC79ChwTPPEyBWZ4b3Y+lAdNDMhvk3U58QmyjYdPbbEyKK384uvrRrJ//fcg+kQcymEi56V1sZ7qq25G0YZUQOPsv/PnE17AW2fDKrD/50vcCU/zn3hjrilVr4Qwb8act0jCJXZo0TXN5P3qwrsAD7g9cENpIRK3VOldmZALeps1VmXnXbG8zcwAJ8AHSh64WfkXdDLXAkQdnYybyVXUFR9k3gicouy3Mf6rR/N+0gGDItifaWneqCYAXPVg7r6lt9fuHGwbTAUyoV1/zPDfN/7CRGQd0LDHG9f0tThFo/ijJtdQTJeohchuB5XwSABr7rKdfvXtuAz/RJ7Hy9BZZBs8e6/RkA6QLj3VEFejAM+ncP+J/aNwAKJyvAFaKTGUZJKrXkQQ1Y5APEQ1S2SPwRTHUxIgoEMl0yflyJ7nrJpcfTDPtxWFG2tONnMn2J70KBo8yQmHpGyd1hPnLZUvdNdHJsYkuXnYQ13vtOT6sZt6fS4kaJRX4Uxf5u3Flq6KhN3BYty2T9ECc6hTyTdnKHmI/3FGsPEfHi/WWO8B/ylukT4y4h6vyvP+GBPeUNXFbRLmnk8dOrU3DqNd1Ta/PZwopLInbtxvyKKWiH7vJB/nad5Al0iO4=
jobs:
  include:
  - stage: test
    script: yarn run test
deploy:
  # Deploy lessestwrong
  - provider: script
    script: 
      yarn;
      cp ./LessWrong-Credentials/mup-lessestwrong.secret ./mup-lessestwrong.secret;
      bash ./travis_wait "mup deploy --config mup-lessestwrong.secret --settings ./LessWrong-Credentials/settings-staging-lessestwrong.json"
    on:
      branch: devel
    skip_cleanup: true
  # Deploy baserates
  - provider: script
    script: 
      yarn;
      cp ./LessWrong-Credentials/mup-baserates.secret ./mup-baserates.secret;
      bash ./travis_wait "mup deploy --config mup-baserates.secret --settings ./LessWrong-Credentials/settings-staging-baserates.json"
    on:
      branch: devel
    skip_cleanup: true
  # Deploy production
  - provider: script
    script: 
      yarn;
      cp ./LessWrong-Credentials/mup-production.secret ./mup-production.secret;
      bash ./travis_wait "mup deploy --config mup-production.secret --settings ./LessWrong-Credentials/settings-production-lesswrong.json"
    on:
      branch: master
    skip_cleanup: true
  # Deploy Alignment Forum
  - provider: script
    script: 
      yarn;
      cp ./LessWrong-Credentials/mup-af.secret ./mup-af.secret;
      bash ./travis_wait "mup deploy --config mup-af.secret --settings ./LessWrong-Credentials/settings-production-alignmentforum.json"
    on:
      branch: master
    skip_cleanup: true