language: node_js
cache: false
python: 3.7
node_js:
- 12
before_install:
- yarn install
- command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com | /bin/sh
before_script:
- export PATH=$HOME/.meteor:$PATH
jobs:
  include:
  - stage: everything
    name: "Tests"
    script: yarn run test && yarn run lint && yarn run checktypes
  - script: skip
    # TODO: add 'stage' key = 'deploy' so that this step runs in series, not parallel
    #       See https://docs.travis-ci.com/user/build-stages/#how-do-build-stages-work
    name: "Deploy Staging"
    # Maybe ea-forum-staging or ea-forum-devel
    if: branch = ci-deploy AND type != pull_request
    deploy: &staging
      provider: script
      script: bash ./deploy.sh ./settings-staging.json ./config-staging.secret
      on:
        branch: ci-deploy
  # - script: skip
  #   name: "Deploy LessWrong"
  #   if: branch = master AND type != pull_request
  #   deploy: &lesswrong
  #     provider: script
  #     script:
  #       bash ./deploy.sh ./LessWrong-Credentials/settings-production-lesswrong.json ./LessWrong-Credentials/mup-production.secret
  #     on:
  #       branch: master
