branch-defaults:
  expressNotMeteor:
    environment: LessWrong2Express-dev3
  tryDeploying:
    environment: LessWrong2Express-dev3
environment-defaults:
  LessWrong2Express-dev3:
    branch: null
    repository: null
global:
  application_name: Lesswrong2
  branch: null
  default_ec2_keyname: LessWrong-Express-SSH
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
