branch-defaults:
  ea-dev:
    environment: EAForum-Staging
    group_suffix: null
  mergeLWMaster:
    environment: EAForum-Staging-2
global:
  application_name: EAForum
  branch: null
  default_ec2_keyname: cea_devops
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
