branch-defaults:
  tryDeploying:
    environment: LessWrong2Express-dev4
    group_suffix: null
global:
  application_name: LessWrongExpress
  branch: null
  default_ec2_keyname: LessWrong-Express-SSH
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
