branch-defaults:
  fixedGithubActions:
    environment: null
    group_suffix: null
global:
  application_name: mup-lesswrong2-baserates
  branch: null
  default_ec2_keyname: LessWrong
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
