# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ expressNotMeteor, tryDeploying ]
  pull_request:
    branches: [ expressNotMeteor ]

- name: AWS Elastic Beanstalk cli
  uses: hmanzur/actions-aws-eb@v1
    with:
      command: 'deploy ${{ secrets.ENVIRONMENT_NAME }}'
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: "us-east-1"